### ISSUE TITLE
Several links in the doc are broken

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum-habana#100]
For example https://huggingface.co/docs/optimum.habana/main/en/trainer#optimum.habana.GaudiTrainer in https://huggingface.co/docs/optimum/main/en/habana_single_hpu
Or https://github.com/huggingface/optimum.habana/blob/main/optimum/habana/trainer.py#L97 in https://huggingface.co/docs/optimum/main/en/habana_trainer#optimum.habana.GaudiTrainer

The first one seem to be broken because it uses `optimum.habana` instead of `optimum`, and the path `main/en/trainer` instead of `main/en/habana_trainer`.

The second one because it uses `optimum.habana` instead of `optimum-habana` in the github path.

@regisss

**Comment by regisss** [comment]
Thanks @fxmarty for spotting this! I'm going to fix it.
