### ISSUE TITLE
Unable to run protein-folding example with the latest release: optimum-habana-1.11.1

### ISSUE THREAD

**Issue by mgujral** [huggingface/optimum-habana#1014]
### System Info

```shell
optimum-habana-1.11.1
optimum==1.19.1
SynapseAI version: 1.15.1
Docker image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest

When I launch the protein-folding example, I get the following message. However, with the older release of optimum-habana-1.9.0 and SynapseAI version 1.13  protein-folding example worked fine.

/home/mgujral/optimum-habana-1.11.1/transformers/utils/generic.py:462: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.reg
ister_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/mgujral/optimum-habana-1.11.1/transformers/utils/generic.py:319: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.reg
ister_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/mgujral/optimum-habana-1.11.1/transformers/utils/generic.py:319: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.reg
ister_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/mgujral/optimum-habana-1.11.1/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads alway
s resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of EsmForProteinFolding were not initialized from the model checkpoint at facebook/esmfold_v1 and are newly initialized: ['esm.contact_head.regression.bias', 'esm
.contact_head.regression.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
============================= HABANA PT BRIDGE CONFIGURATION =========================== 
 PT_HPU_LAZY_MODE = 1
 PT_RECIPE_CACHE_PATH = 
 PT_CACHE_FOLDER_DELETE = 0
 PT_HPU_RECIPE_CACHE_CONFIG = 
 PT_HPU_MAX_COMPOUND_OP_SIZE = 9223372036854775807
 PT_HPU_LAZY_ACC_PAR_MODE = 1
 PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES = 1
---------------------------: System Configuration :---------------------------
Num CPU Cores : 96
CPU RAM       : 527939920 KB
------------------------------------------------------------------------------
Synapse detected a device critical error that requires a restart. Killing process in 5 seconds (hl: 7) 02:10:00 [please check log files for dfa cause]
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python3 run_esmfold.py

It does not have any requirements.

### Expected behavior

The run should generate protein structure file with extension pdb.

**Comment by mgujral** [comment]
<img width="1245" alt="esmfold" src="https://github.com/huggingface/optimum-habana/assets/23059680/ddd10188-2101-4fb0-95de-26c3d63c15e9">

**Comment by mgujral** [comment]
This is the easiest tool to run. I do not know what is going on?

**Comment by mgujral** [comment]
<img width="640" alt="hl-smi" src="https://github.com/huggingface/optimum-habana/assets/23059680/425c30e9-fcbb-4b15-8d49-c8d714da3f75">

**Comment by mgujral** [comment]
I am using Gaudi HPU nodes.

**Comment by libinta** [comment]
@mgujral  Can you collect logs with HABANA_PROFILE=./log LOG_LEVEL_ALL=0 before your cmd? And attach the log folder?
Thanks.

**Comment by mgujral** [comment]
[logsForGithub.tgz](https://github.com/huggingface/optimum-habana/files/15476428/logsForGithub.tgz)

These are logs before launching the command. Appreciate your help!!!

**Comment by mgujral** [comment]
I looked at the file 'dfa_log.txt', and it had the following message at top. Any thoughts what does it mean?

 hl thunk API failed, errCode memcopyIoctlFailed

**Comment by mgujral** [comment]
When I try with 8-HPU cards, warning and error messages are same as before. Altering the line run_esmfold.py#L85 does not make any difference either. When I check memory usage with 'top' command, max memory usage goes too about 4.5%. I notice one more thing, when I try any application in language-modelling folder I get the identical 'Synapse detected a device critical error......' error message.

grep Huge /proc/meminfo

AnonHugePages:         0 kB
ShmemHugePages:        0 kB
FileHugePages:         0 kB
HugePages_Total:   48000
HugePages_Free:    48000
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:        98304000 kB

**Comment by libinta** [comment]
when you said you try with 8-hpu card, you are still using python [run_esmfold.py](https://github.com/huggingface/optimum-habana/blob/main/examples/protein-folding/run_esmfold.py) , not gaudi_spawn 8x, right? can you also do sudo dmesg -T >dmesg.txt? thx

**Comment by mgujral** [comment]
Yes, with 8-hpu card, I am  still using python run_esmfold.py. Thank you for your patience & time.
[dmesg.txt](https://github.com/huggingface/optimum-habana/files/15491535/dmesg.txt)

**Comment by libinta** [comment]
seems except the pin memory issue, nothing print out. looks like machine already in this bad state. are you on aws? and is the issue only happening to this pod? thx

**Comment by mgujral** [comment]
I am on Voyager cluster at UCSD. It is a dedicated AI machine with 36 Intel-Habana Gaudi nodes. We have recently switched to driver version 1.15.1 and SynapseAI image 1.15.1. This problem only started with switch to 1.15.1. I had notified it to Intel-Habana team and they told me  to raise  the issue with Huggingface-Habana on Github.

**Comment by libinta** [comment]
thanks for the information. are you running the same optimum-habana version before and after the Synapse SW upgrade?

**Comment by mgujral** [comment]
No, I updated to the version recommended for SynsapseAI 1.15.1. If you scroll to the top, you can see the versions.

**Comment by libinta** [comment]
which optimum-habana version are you using before 1.15.1 update? and which synapse sw version you had before?
For debug purpose, can you switch to the old optimum-habana version working with your previous synapse version and try ?

**Comment by mgujral** [comment]
Earlier I was using SynapsAI 1.13.0 with optimum-habana==1.9.0 and optimum==1.14.1. Applications were working fine.

**Comment by mgujral** [comment]
I went to SynapseAI image 1.13.0 and used appropriate PYTHONPATH, and things worked fine as they should.

python run_esmfold.py 
/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py:252: UserWarning: Device capability of hccl unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
Some weights of EsmForProteinFolding were not initialized from the model checkpoint at facebook/esmfold_v1 and are newly initialized: ['esm.contact_head.regression.bias', 'esm.contact_head.regression.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
============================= HABANA PT BRIDGE CONFIGURATION =========================== 
 PT_HPU_LAZY_MODE = 1
 PT_RECIPE_CACHE_PATH = 
 PT_CACHE_FOLDER_DELETE = 0
 PT_HPU_RECIPE_CACHE_CONFIG = 
 PT_HPU_MAX_COMPOUND_OP_SIZE = 9223372036854775807
 PT_HPU_LAZY_ACC_PAR_MODE = 1
 PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES = 0
---------------------------: System Configuration :---------------------------
Num CPU Cores : 96
CPU RAM       : 527939884 KB
------------------------------------------------------------------------------
ESMFOLD: input shape = torch.Size([1, 350])
ESMFOLD: step 0 start ...
ESMFOLD: step 0 duration: 70.469 seconds
ESMFOLD: step 1 start ...
ESMFOLD: step 1 duration: 36.434 seconds
ESMFOLD: step 2 start ...
ESMFOLD: step 2 duration: 14.153 seconds
ESMFOLD: step 3 start ...
ESMFOLD: step 3 duration: 14.138 seconds
pdb file saved in save-hpu.pdb

**Comment by mgujral** [comment]
I used only 1-HPU card.

**Comment by libinta** [comment]
can you go back to 1.9.0 and 1.14.1 to check with synapse 1.15.1?

**Comment by mgujral** [comment]
This is what I get.
/usr/bin/python run_esmfold.py 
Traceback (most recent call last):
  File "/home/mgujral/huggingface-habana/optimum-habana-1.11.1/examples/protein-folding/run_esmfold_original.py", line 20, in <module>
    import habana_frameworks.torch.core as htcore
  File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/__init__.py", line 17, in <module>
    import torch
  File "/home/mgujral/deepspeedForImage_1.3.0/torch/__init__.py", line 519, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

**Comment by libinta** [comment]
I didn't see any issue with optimum-habana 1.9.0, the way I did is to git checkout v1.9.0, inside docker
go to optimum-habana, do "pip install -e ."
then go to examples/protein-folding/, do "python run_esmfold.py

**Comment by mgujral** [comment]
Thank for for all your help, I shall take up the matter with Intel-Habana team.

**Comment by mgujral** [comment]
The problem has been resolved. This line 'hugepages-2Mi: 95000Mi' was missing from my yaml file, and error messages I was getting were misleading.
