### ISSUE TITLE
does the optimum-habana support sdxl controlnet image to image pipeline?

### ISSUE THREAD

**Issue by basantaxpatra** [huggingface/optimum-habana#1103]
### System Info

```shell
Working on a solution for Image-to-Image with multi controlnet conditions. Don't see any sample available.
Currently only 2 samples i see (text-to-image and text-to-video).
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

No sample for image to image with controlnet pipeline (SDXL)

### Expected behavior

Reference sample is helpful

**Comment by regisss** [comment]
There are some open PRs about image-to-image generation, like #869 and #988. They should be merged into main soon.
Is it what you're looking for?

**Comment by dsocek** [comment]
@basantaxpatra FYI here is a functional SDXL + CN on Gaudi (still working on adding batching so didn't create PR yet):  https://github.com/dsocek/optimum-habana/tree/sdxlcn
