### ISSUE TITLE
Data  parallelism or tensor  parallelism? How can i know that and is there a chance i can shift in between these too?

### ISSUE THREAD

**Issue by venkycreator** [huggingface/optimum-habana#1242]
### System Info

```shell
in the run_generation.py (for text generation) How can i know that what kind of parallelism it is like data or tensor? and is there a chance to shift in between these two?
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I wanted to know in order to rum the models parallel using deepspeed 

### Expected behavior

wanted to know what kind of parallelism it supports

**Comment by regisss** [comment]
@venkycreator This example doesn't offer any data parallelism. It could be added wrapping the model with PyTorch DistributedDataParallel.

Tensor parallelism is possible either using DeepSpeed or adding the argument `--parallel_strategy tp`.
