### ISSUE TITLE
runwayml/stable-diffusion-v1-5 no longer exists

### ISSUE THREAD

**Issue by vidyasiv** [huggingface/optimum-habana#1305]
Less of a bug and more of a question.
Huggingface no longer has this model : https://huggingface.co/runwayml/stable-diffusion-v1-5
but it's referenced all over the repository in examples and gives a 404 client error. Not sure if this happens often or is some transient issue but what is a good equivalent to use?

Can also start a PR replacing with available model if you think it's a good idea to do so.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Reference: https://github.com/huggingface/optimum-habana/tree/main/examples/stable-diffusion#single-prompt-1
```
pip install .
cd examples/stable-diffusion
pip install -r requirements.txt
python image_to_image_generation.py     --model_name_or_path "runwayml/stable-diffusion-v1-5"     --src_image_path "https://raw.githubuserc
ontent.com/timothybrooks/instruct-pix2pix/main/imgs/example.jpg"     --prompts "turn him into cyborg"     --num_images_per_prompt 20     --batch_size 4     --guidance_scale 7.5     --image_guidance_scale 1     --num_inference_steps 10     --image_save_dir /tmp/stable_diffusion_images     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --bf16
```

### Expected behavior

Model would get downloaded

**Comment by regisss** [comment]
The owners of https://huggingface.co/runwayml/stable-diffusion-v1-5 decided to take it down so it's not on the hub anymore.
I think the best is to replace all the occurrences of this model in examples and tests by https://huggingface.co/CompVis/stable-diffusion-v1-4. WDYT?

**Comment by vidyasiv** [comment]
> The owners of https://huggingface.co/runwayml/stable-diffusion-v1-5 decided to take it down so it's not on the hub anymore. I think the best is to replace all the occurrences of this model in examples and tests by https://huggingface.co/CompVis/stable-diffusion-v1-4. WDYT?

Also an issue upstream(I had forgotten to check earlier), perhaps we can follow their lead on this: https://github.com/huggingface/diffusers/issues/9322.

**Comment by regisss** [comment]
I opened https://github.com/huggingface/optimum-habana/pull/1315 which should fix this issue (among other things).
