### ISSUE TITLE
Flash attention not supported in run_clm.py

### ISSUE THREAD

**Issue by aitss2017** [huggingface/optimum-habana#1318]
### System Info

```shell
HL-SMI Version: hl-1.17.0-fw-51.3.0        
Driver Version: 1.17.0-28a11ca  
Docker image: vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1
deepspeed                   0.14.0+hpu.synapse.v1.17.0
habana_gpu_migration        1.17.0.495
habana-media-loader         1.17.0.495
habana-pyhlml               1.17.0.495
habana_quantization_toolkit 1.17.0.495
habana-torch-dataloader     1.17.0.495
habana-torch-plugin         1.17.0.495
optimum-habana              1.14.0.dev0
torch                       2.3.1a0+git4989238
torch_tb_profiler           0.4.0
torchaudio                  2.3.0+952ea74
torchdata                   0.7.1+5e6f7b7
torchmetrics                1.4.0.post0
torchtext                   0.18.0a0+9bed85d
torchvision                 0.18.1a0+fe70bc8
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

PT_HPU_MAX_COMPOUND_OP_SIZE=10 DEEPSPEED_HPU_ZERO3_SYNC_MARK_STEP_REQUIRED=1 PT_HPU_ENABLE_LAZY_COLLECTIVES=true \
python ../gaudi_spawn.py \
    --use_deepspeed --world_size 8 run_clm.py \
    --model_name_or_path /DISK0/Mistral-7B-v0.3/ \
    --dataset_name  /DISK0/alpaca \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --do_train \
    --do_eval \
    --output_dir /tmp/mistral_7b \
    --use_habana \
    --use_lazy_mode \
    --gradient_checkpointing \
    --throughput_warmup_steps 3 \
    --deepspeed ./llama2_ds_zero3_config.json \
    --gaudi_config_name gaudi_config.json \
    --trust_remote_code True \
    --overwrite_output_dir \
    --block_size 4096 \
    --save_strategy epoch \
    --use_flash_attention

### Expected behavior

Fix below flash attention support in run_clm.py

[rank0]: Traceback (most recent call last):
[rank0]:   File "/DISK1/optimum-habana/examples/language-modeling/run_clm.py", line 695, in <module>
[rank0]:     main()
[rank0]:   File "/DISK1/optimum-habana/examples/language-modeling/run_clm.py", line 269, in main
[rank0]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/hf_argparser.py", line 348, in parse_args_into_dataclasses
[rank0]:     raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
[rank0]: ValueError: Some specified arguments are not used by the HfArgumentParser: ['--use_flash_attention']

**Comment by regisss** [comment]
This is not a defined argument, so this cannot work. To make it work in the CLM example, you need to:
- set `model.generation_config=True` before [this line](https://github.com/huggingface/optimum-habana/blob/85704533518c6c1d54a144dc7a739f30a36ec6c2/examples/language-modeling/run_clm.py#L621)
- add "mistral" to the lists [here](https://github.com/huggingface/optimum-habana/blob/85704533518c6c1d54a144dc7a739f30a36ec6c2/optimum/habana/transformers/trainer.py#L966) and [there](https://github.com/huggingface/optimum-habana/blob/85704533518c6c1d54a144dc7a739f30a36ec6c2/optimum/habana/transformers/trainer.py#L1873)

That's weird though that we didn't add it to these two lists in the GaudiTrainer class. Feel free to try and if it works we can open a PR to add these changes.

**Comment by aitss2017** [comment]
I pull latest master branch and modified above code, while it still not work.
Same error: [rank0]: ValueError: Some specified arguments are not used by the HfArgumentParser: ['--use_flash_attention']

PT_HPU_MAX_COMPOUND_OP_SIZE=10 DEEPSPEED_HPU_ZERO3_SYNC_MARK_STEP_REQUIRED=1 PT_HPU_ENABLE_LAZY_COLLECTIVES=true \
python ../gaudi_spawn.py \
    --use_deepspeed --world_size 8 run_clm.py \
    --model_name_or_path /DISK0/Mistral-7B-v0.3/ \
    --dataset_name  /DISK0/alpaca \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --do_train \
    --do_eval \
    --output_dir /tmp/mistral_7b \
    --use_habana \
    --use_lazy_mode \
    --gradient_checkpointing \
    --throughput_warmup_steps 3 \
    --deepspeed ./llama2_ds_zero3_config.json \
    --gaudi_config_name gaudi_config.json \
    --trust_remote_code True \
    --overwrite_output_dir \
    --block_size 4096 \
    --save_strategy epoch \
    --use_flash_attention

**Comment by regisss** [comment]
You will get this error as long as you pass `--use_flash_attention` while it is not defined as an argument in this class: https://github.com/huggingface/optimum-habana/blob/45c114f82d2eea10745f650a684a16075f6075f6/examples/language-modeling/run_clm.py#L76

**Comment by aitss2017** [comment]
It seems that  even I add use flash attention option in run_clm.py, I met new error:

[rank7]:   File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/mistral/modeling_mistral.py", line 721, in forward
[rank7]:     if self.generation_config.use_fused_rope is False:
[rank7]: AttributeError: 'bool' object has no attribute 'use_fused_rope'

Can you help look into this feature to see if we should add flash attention in run_clm.py?
After all not all models can support flash attention.

**Comment by regisss** [comment]
My bad, I made a mistake in https://github.com/huggingface/optimum-habana/issues/1318#issuecomment-2337586963.
I just edited it, basically it should be `model.generation_config.use_flash_attention=True` and not `model.generation_config=True`.
Can you try again and let me know what you get please?
