### ISSUE TITLE
Tokenizer error: eos_token_id not found error - Incorrect assignment of variables

### ISSUE THREAD

**Issue by premmotgi** [huggingface/optimum-habana#1326]
Incorrect assignment:
https://github.com/huggingface/optimum-habana/blob/feb6545202ef6812445bbca680eb3ad50ffe5aa8/examples/language-modeling/run_lora_clm.py#L704

When running a model customization for 8B and 70B with customized dataset such as databricks-dolly-15k. I get error related to Tokenizer class does not have add_eos_token_id variable in it. 

When I looked into the code the assignments look ambiguous and need to be corrected to avoid runtime errors. tokenizer.add_eos_token is not yet initialised and before even initializing it cannot be assigned to a temp variable.

If the goal is to assign value to or initialize  tokenizer.add_eos_token then best would be to use the function argument directly.

Correct code would be 
```
add_eos_token_o = add_eos_token #assign value from function argument

OR

tokenizer.add_bos_token = add_bos_token_o #directly assign value to tokenizer object

```

**Comment by mengker33** [comment]
I also encountered this error and https://github.com/huggingface/optimum-habana/pull/1253 caused it, looks like the author didn't check very clearly if all the tokenizer has the attribute "add_eos_token"  (only llama tokenizer class is checked here https://github.com/huggingface/optimum-habana/pull/1253#discussion_r1744688859)

**Comment by regisss** [comment]
@premmotgi @mengker33 Can you give me an example of tokenizer that doesn't work with this example please?

**Comment by mengker33** [comment]
Hi @regisss, I updated my local branch and found the issue is gone. The commit https://github.com/huggingface/optimum-habana/commit/fdbb7191c150fb149db3d8ff96edbad0233083ab has fixed it.
