### ISSUE TITLE
Dataset v3.0.0 deprecates tasks and cause CI failures

### ISSUE THREAD

**Issue by vidyasiv** [huggingface/optimum-habana#1341]
### System Info

```shell
Main: Latest
Docker: 1.18.0/1.17.0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Test run:
```
pytest -v -s tests/test_examples.py -k test_run_speech_recognition_ctc_wav2vec2-large-lv60_multi_card
```

Output:
```
[rank2]:     from datasets.tasks import AutomaticSpeechRecognition
[rank2]: ModuleNotFoundError: No module named 'datasets.tasks'
```
This is from https://huggingface.co/datasets/regisss/librispeech_asr_for_optimum_habana_ci/blob/main/librispeech_asr_for_optimum_habana_ci.py#L23

Reason is datasets v3.0.0 removes tasks per [release notes](https://github.com/huggingface/datasets/releases) and [PR](https://github.com/huggingface/datasets/pull/6999)
Possibly we need to downgrade datasets or find an alternative implementation that works with v3.0.0

### Expected behavior

Test should pass

**Comment by vidyasiv** [comment]
@regisss , please review PR: https://huggingface.co/datasets/regisss/librispeech_asr_for_optimum_habana_ci/discussions/1/

**Comment by regisss** [comment]
It should work now with https://huggingface.co/datasets/regisss/librispeech_asr_for_optimum_habana_ci/commit/e15120eeee593aff1ed38f987d99ac30cd17a168.
It's the same change as for the original dataset: https://huggingface.co/datasets/openslr/librispeech_asr/commit/85efb3e7036e87a84b6ecf630b7d168b3c2c2696

Does the test pass on your side?

**Comment by regisss** [comment]
> @regisss , please review PR: https://huggingface.co/datasets/regisss/librispeech_asr_for_optimum_habana_ci/discussions/1/

Arf sorry I didn't see this comment :/

**Comment by vidyasiv** [comment]
> > @regisss , please review PR: https://huggingface.co/datasets/regisss/librispeech_asr_for_optimum_habana_ci/discussions/1/
> 
> Arf sorry I didn't see this comment :/

No problem, I am getting past the failure now thanks.
