### ISSUE TITLE
Pretrain with LLama Model - num_samples=0 Error

### ISSUE THREAD

**Issue by saisuryateja1436** [huggingface/optimum-habana#1396]
### System Info

```shell
vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When I tried to run run_clm.py file from Language Modelling with llama3.1 model, I am running into a error saying num_samples=0

[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 143, in __init__
[rank6]:     raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
[rank6]: ValueError: num_samples should be a positive integer value, but got num_samples=0

when I tried to do the same with gpt2-xl it is working

![image](https://github.com/user-attachments/assets/a8717562-30e7-4f99-a631-abca2c357160)

### Expected behavior

Pretraining of Llama model

**Comment by regisss** [comment]
Can you please share the command you ran?

**Comment by saisuryateja1436** [comment]
This is for gpt2

CMD ["python3", "../gaudi_spawn.py", "--world_size", "1", "--use_deepspeed", "run_clm.py", "--model_name_or_path", "gpt2-xl", "--train_file", "dataset_update.txt", "--per_device_train_batch_size", "16", "--per_device_eval_batch_size", "4", "--do_train", "--do_eval", "--learning_rate", "4e-4", "--output_dir", "test-clm", "--gaudi_config_name", "Habana/gpt2", "--use_habana", "--use_lazy_mode", "--use_hpu_graphs_for_inference", "--gradient_checkpointing", "--use_cache", "False", "--throughput_warmup_steps", "3", "--deepspeed", "config"] 

This is for Llama3 
CMD ["python3", "../gaudi_spawn.py", "--world_size", "1", "--use_deepspeed", "run_clm.py", "--model_name_or_path", "meta-llama/Llama-3.1-8B", "--train_file", "dataset_update.txt", "--per_device_train_batch_size", "16", "--per_device_eval_batch_size", "4", "--do_train", "--do_eval", "--learning_rate", "4e-4", "--output_dir", "test-clm", "--gaudi_config_name", "Habana/llama", "--use_habana", "--use_lazy_mode", "--use_hpu_graphs_for_inference", "--gradient_checkpointing", "--use_cache", "False", "--throughput_warmup_steps", "3", "--deepspeed", "config"]

**Comment by regisss** [comment]
I think there is an issue with `--train_file dataset_update.txt`. Is it possible to share this file or let me know its structure?

**Comment by saisuryateja1436** [comment]
![image](https://github.com/user-attachments/assets/280911d2-9db5-4cc2-8e8d-9ce7e644e21e)
I actually solved that issue. But now I am getting another error. can you check this one

**Comment by regisss** [comment]
Can you copy-paste the command you ran here please?
Also, can you let me know the versions of Optimum Habana and of SynapseAI you use and the output of `hl-smi` please?

**Comment by saisuryateja1436** [comment]
![image](https://github.com/user-attachments/assets/1f8e19a0-c38c-41b0-b881-2175e51c415f)

**Comment by saisuryateja1436** [comment]
habana version is 4.43 
Allocation error was due to small world size. It was solved increasing the world size
But I am getting the same error as  num_samples =0 
where as using the same command with gpt2-xl I was able to train

**Comment by regisss** [comment]
Can you share the two commands? Are you still using a custom dataset file?

**Comment by saisuryateja1436** [comment]
yes I wanted to use custom one, but the hugging face dataset is also not working 

Commands:
This is for gpt2

CMD ["python3", "../gaudi_spawn.py", "--world_size", "1", "--use_deepspeed", "run_clm.py", "--model_name_or_path", "gpt2-xl", "--train_file", "dataset_update.txt", "--per_device_train_batch_size", "16", "--per_device_eval_batch_size", "4", "--do_train", "--do_eval", "--learning_rate", "4e-4", "--output_dir", "test-clm", "--gaudi_config_name", "Habana/gpt2", "--use_habana", "--use_lazy_mode", "--use_hpu_graphs_for_inference", "--gradient_checkpointing", "--use_cache", "False", "--throughput_warmup_steps", "3", "--deepspeed", "config"]

This is for Llama3

CMD ["python3", "../gaudi_spawn.py", "--world_size", "1", "--use_deepspeed", "run_clm.py", "--model_name_or_path", "meta-llama/Llama-3.1-8B", "--train_file", "dataset_update.txt", "--per_device_train_batch_size", "16", "--per_device_eval_batch_size", "4", "--do_train", "--do_eval", "--learning_rate", "4e-4", "--output_dir", "test-clm", "--gaudi_config_name", "Habana/llama", "--use_habana", "--use_lazy_mode", "--use_hpu_graphs_for_inference", "--gradient_checkpointing", "--use_cache", "False", "--throughput_warmup_steps", "3", "--deepspeed", "config"]

**Comment by saisuryateja1436** [comment]
The issue is with dataset.. llama requires larger dataset as it's context window is 128k. we can overcome this problem by mentioning block size
