### ISSUE TITLE
Run text-generation with non-deepspeed mode

### ISSUE THREAD

**Issue by ZhaiFeiyue** [huggingface/optimum-habana#213]
### Feature request

Current [text-generation](https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation) only support bloom & bloomz with deepspeed, but not support other generation model like gpt2, gpt-j, neox.
There also a [PR](https://github.com/huggingface/optimum-habana/pull/209) shows how to run inference in each of examples, but the inference is training evaluation not a real generation case.
so is there any possible to support the following features?
- `text-generation` support other generation model(e.g. gpt2, gpt-j)
- `text-generation` support non-deepspeed mode

### Motivation

text-generation only support bloom and bloomz, can not run text-generation with gpt2, gpt-j, neox,...

### Your contribution

submitting a PR

**Comment by ZhaiFeiyue** [comment]
@regisss is there any possible to adding gpt2, neox, gpt-j into text-generation?

**Comment by regisss** [comment]
@ZhaiFeiyue Yep I'm going to start working on it today. I'll add you as a reviewer when the PR is ready :slightly_smiling_face:

**Comment by regisss** [comment]
@ZhaiFeiyue I updated the bloom branch to be able to run models on 1 device without DS-inference: https://github.com/huggingface/optimum-habana/tree/bloom/examples/text-generation

I'm going to test a few more things before opening a PR.

**Comment by regisss** [comment]
@ZhaiFeiyue I opened a PR here: #218. It would be great if you can review it :slightly_smiling_face: 

I also added you to the repo with write permissions. I think you should have got an invite. That way you can push directly to this repo to have all the CI working (we are still investigating how to enable launching DL1 instances from forks...).

**Comment by ZhaiFeiyue** [comment]
thank you @regisss , I will review PR #218 today.

**Comment by ZhaiFeiyue** [comment]
let's close this issue and work on the PR #218 🙂
