### ISSUE TITLE
GPT2 support bf16 for both training and inferecne

### ISSUE THREAD

**Issue by ZhaiFeiyue** [huggingface/optimum-habana#230]
### Feature request

enable HMP for GPT2

### Motivation

BF16 has better performance than FP32

### Your contribution

submitting a PR

**Comment by ZhaiFeiyue** [comment]
@regisss I have tested the perf between FP32 and BF16, data is below on Gaudi2.

- 1X

|precision| train_samples_per_second|  eval perplexity|
|-|-|-|
| FP32| 47.624|21.0109|
|BF16 |55.511 | 21.177|

- 8X

|precision| train_samples_per_second|  eval perplexity|
|-|-|-|
| FP32| 306.631| 21.7935|
|BF16 | 357.932|22.1765 |

is the above accuracy acceptable?

**Comment by regisss** [comment]
Yes it seems good to me!

For this, what you should actually do is to open a PR on the HF Hub [here](https://huggingface.co/Habana/gpt2/blob/main/gaudi_config.json): click on "edit" and :
- Set `use_habana_mixed_precision": true`
- Add the list of bf16/fp32 ops such as it is done [there](https://huggingface.co/Habana/roberta-base/blob/main/gaudi_config.json) for instance. Or are they the default ones?

**Comment by ZhaiFeiyue** [comment]
@regisss  I have opened a [PR](https://huggingface.co/Habana/gpt2/discussions/2), for your question, most of BF16 ops are same with the default, but `mul` should be FP32, since there is a accuracy bug(nan issue) from [here]( https://github.com/huggingface/transformers/blob/3335724376319a0c453049d0cd883504f530ff52/src/transformers/models/gpt2/modeling_gpt2.py#L823)

**Comment by regisss** [comment]
> yes, I will submit a PR to disable HMP [here](https://github.com/huggingface/transformers/blob/3335724376319a0c453049d0cd883504f530ff52/src/transformers/models/gpt2/modeling_gpt2.py#L823), and should I remove `mul` from FP32 list from [here](https://huggingface.co/Habana/gpt2/blob/main/gaudi_config.json#L23) or remove all the BF16 and FP32 ops and just change `use_habana_mixed_precision": true` ?

I think you can just remove `mul` in the Gaudi config of GPT2, that will make things clearer regarding which ops are computed in bf16.

**Comment by ZhaiFeiyue** [comment]
@regisss I will follow your comments after PR #232 merged.

**Comment by regisss** [comment]
@ZhaiFeiyue We can close this one right?

**Comment by ZhaiFeiyue** [comment]
@regisss  yes
