### ISSUE TITLE
Adding profiling

### ISSUE THREAD

**Issue by ZhaiFeiyue** [huggingface/optimum-habana#245]
### Feature request

HabanaAI support PyTorch profiler, and currently if user want to figure out the bottleneck of training or inference, they should modify the source code(`adding torch.profiler` into `GaudiTrainer `or `generate`), with which  the user experience is not good.
If we support `torch.profiler` in optimum-habana, and user could generate the profiling data just with `--do_profiling 10`
- default value of do_profiling  is 0, means not generate the profiling data
- 10 means how many steps or iterations will be captured

refer [profiling-with-pytorch](https://docs.habana.ai/en/latest/Profiling/Profiling_with_PyTorch.html?highlight=profiling)

### Motivation

- easy to address the bottleneck of model both for training and inference

### Your contribution

submit a PR

**Comment by ZhaiFeiyue** [comment]
@regisss is there any possible that we support such kind of feature?

**Comment by regisss** [comment]
@ZhaiFeiyue Sounds good to me! Do you want to open a PR to add this?

**Comment by ZhaiFeiyue** [comment]
@regisss I will do that

**Comment by ZhaiFeiyue** [comment]
fixed by PR #250, and close
