### ISSUE TITLE
Enable beam_search for text-generation

### ISSUE THREAD

**Issue by ZhaiFeiyue** [huggingface/optimum-habana#270]
### Feature request

currently test-generation only support beam=1,which is not exposed to users, any possible that expose --beams user?

### Motivation

enable beam_search algo path if beams > 1 and beams =1 falls into greedy_search

### Your contribution

submit a PR

**Comment by ZhaiFeiyue** [comment]
@regisss  I have noticed that you have enabled beam_search path([here](https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L1517)) but not exposed `--beams` to user.

have you tested beam_search path before, since on Gaudi,  we can't concat the `input_ids` and `new_tokens` together see [here](https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L1787), we should use `token_idx` to insert the new tokens into `input_ids`.  you have made such kind of changes for `sample` and `greedy_search`, so I think you forget do that for `beam_search`, am I right?

**Comment by ZhaiFeiyue** [comment]
I also create a quick Fix @regisss  please have a look if I am right.

**Comment by regisss** [comment]
Well, it's not really that I forgot to do it (it was in my to-do list), I just have not got the time to work on it lately XD
Thanks for proposing a PR to enable it, I'll take a look at it today!
