### ISSUE TITLE
RuntimeError: Device acquire failed. in /usr/local/lib/python3.8/dist-packages/habana_frameworks/torch/hpu/__init__.py"

### ISSUE THREAD

**Issue by Abhaycnvrg** [huggingface/optimum-habana#288]
### System Info

```shell
Optimum Habana : 1.6.0
SynapseAI : 1.4.0
Docker Image : Deep Learning AMI Habana PyTorch 1.10.2 SynapseAI 1.4.0 (Ubuntu 20.04) 20220425
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Start an EC2 instance with DL1 Resource and this image : 
2. Install "Deep Learning AMI Habana PyTorch 1.10.2 SynapseAI 1.4.0 (Ubuntu 20.04) 20220425"
3. Run these commands
a. docker run -it --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host --ipc=host vault.habana.ai/gaudi-docker/1.10.0/ubuntu20.04/habanalabs/pytorch-installer-2.0.1:latest
b. git clone https://github.com/huggingface/optimum-habana.git
c. cd optimum-habana && python setup.py install
d. cd examples
e. cd text-generation
f. pip install -r requirements.txt
e. python run_generation.py \
--model_name_or_path gpt2 \
--use_hpu_graphs \
--use_kv_cache \
--max_new_tokens 100 \
--do_sample \
--prompt "Tell me a poem about stone and water"

### Expected behavior

Should get the desired text (poem about stone and water)

**Comment by regisss** [comment]
Hi @Abhaycnvrg, you should use an AMI that features SynapseAI 1.10.0 like "Habana® Deep Learning Base AMI (Ubuntu 20.04)".
The one you use, "Deep Learning AMI Habana PyTorch 1.10.2 SynapseAI 1.4.0 (Ubuntu 20.04) 20220425", features SynapseAI 1.4.0 and new versions of SynapseAI are not necessarily backwards compatible.
As a general rule of thumb, I strongly recommend to use the latest Habana AMIs.

**Comment by Abhaycnvrg** [comment]
Can you give any sample image that I can use?

**Comment by regisss** [comment]
The one I cited in my previous message for instance: Habana® Deep Learning Base AMI (Ubuntu 20.04)

**Comment by Abhaycnvrg** [comment]
It's working!
Also, can you tell me if I need to test with these models here
https://developer.habana.ai/catalog_tags/large-language-models/
can I just put the name of the model as
bigscience/bloom? 
Will this get the original bloom model or the optimized one you guys created?
And finally,
what to put to get the megatron model? This link is empty
https://huggingface.co/bigscience/bloom-megatron-deepspeed

**Comment by regisss** [comment]
For BLOOM, you'll need to install and use DeepSpeed as I explained in the other issue: https://github.com/huggingface/optimum-habana/issues/289
It will automatically use the optimized version.

Other models like GPT2 for instance will work fine even without DeepSpeed.

Regarding the megatron version, it won't work with Optimum Habana as we have not integrated it into the library. You should rather follow this example if you want to do it: https://github.com/HabanaAI/Model-References/tree/master/PyTorch/nlp/DeepSpeedExamples/Megatron-DeepSpeed
Note that this is mainly for training. For inference, you can just run the command I gave in the other issue.

You can monitor your devices usage with `hl-smi`.

**Comment by Abhaycnvrg** [comment]
If i start another terminal and run this command 
docker run -it --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host --ipc=host vault.habana.ai/gaudi-docker/1.10.0/ubuntu20.04/habanalabs/pytorch-installer-2.0.1:latest
the original model stops running (connection reset)

**Comment by regisss** [comment]
Why do you need to run another Docker container? If it's to run `hl-smi`, you should be able to run it without being in a container.

**Comment by regisss** [comment]
@Abhaycnvrg Let me know if your issue is solved so that we close this.

**Comment by Abhaycnvrg** [comment]
sure we can. thanks!
