### ISSUE TITLE
   return super().__torch_function__(func, types, new_args, kwargs) RuntimeError: [Rank:0] FATAL ERROR :: MODULE:PT_DEVMEM Allocation failed for size::3288334336 (3136)MB

### ISSUE THREAD

**Issue by Abhaycnvrg** [huggingface/optimum-habana#289]
### System Info

```shell
Optimum Habana : 1.6.0
SynapseAI : 1.10.0
Docker Image : Habana® Deep Learning Base AMI (Ubuntu 20.04)
Volume : 1000 GiB
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Start an EC2 instance with DL1 Resource and this image : Habana® Deep Learning Base AMI (Ubuntu 20.04)
Run these commands
a. docker run -it --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host --ipc=host vault.habana.ai/gaudi-docker/1.10.0/ubuntu20.04/habanalabs/pytorch-installer-2.0.1:latest
b. git clone https://github.com/huggingface/optimum-habana.git
c. pip install optimum[habana]
d. cd examples
e. cd text-generation
f. pip install -r requirements.txt
e. python run_generation.py
--model_name_or_path bigscience/bloom
--use_hpu_graphs
--use_kv_cache
--max_new_tokens 100
--do_sample
--prompt "Tell me a poem about stone and water"

### Expected behavior

It should give a sample poem rather than an error

**Comment by Abhaycnvrg** [comment]
My storage is 1 TB and compute is 768 GB, it failed to allocate merely 3.1 GB?

**Comment by regisss** [comment]
For BLOOM, you'll need to install DeepSpeed with
```bash
pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.10.0
```
and then run the command given in this section: https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation#benchmark

One DL1 instance has 8 devices with about 32 GB of memory each (1 TB is your disk space and 768 GB is your host (CPU) RAM, but what matters most is the memory of your devices). On the other hand, BLOOM is a 176B-parameter model, which means that it requires 352GB of memory (in bfloat16) to be loaded on one device. So, since devices have 32 GB of memory each, it's not enough and triggers this error.
The solution is to perform model parallelism with DeepSpeed to split the computation across devices.

**Comment by Abhaycnvrg** [comment]
Thanks for the clarification but the prompt argument isn't working with deepspeed code. (including the gaudi spawn)
How to get the text generation working with deepspeed?

python ../gaudi_spawn.py --use_deepspeed --world_size 8 run_generation.py \
--model_name_or_path bigscience/bloom-7b1 \
--batch_size 1 \
--use_hpu_graphs \
--use_kv_cache \
--max_new_tokens 100
--prompt "Tell me a poem about stone and water" \

this says that --prompt : command not found

**Comment by regisss** [comment]
This command works for me:
```bash
python ../gaudi_spawn.py --use_deepspeed --world_size 8 run_generation.py \
--model_name_or_path bigscience/bloom-7b1 \
--batch_size 1 \
--use_hpu_graphs \
--use_kv_cache \
--max_new_tokens 100 \
--prompt "Tell me a poem about stone and water"
```

Note that BLOOM won't fit on the 8 devices, even with model parallelism (you should use Gaudi2 to run it) so here I run the 7B-parameter checkpoint.
You can also add `--do_sample` for more realistic generations.

**Comment by Abhaycnvrg** [comment]
gaudi2 means use a different resource than dl1large?

**Comment by regisss** [comment]
Gaudi2 is available on the Intel Developer Cloud, not on AWS. See here how to get access to it: https://huggingface.co/blog/habana-gaudi-2-benchmark#how-to-get-access-to-gaudi2

**Comment by Abhaycnvrg** [comment]
Thanks

I just ran this

python ../gaudi_spawn.py --use_deepspeed --world_size 8 run_generation.py --model_name_or_path bigscience/bloomz --batch_size 1 --use_hpu_graphs --use_kv_cache --max_new_tokens 200

but it again ran into memory issue (failed to allocate)
I assume that it's because bloom is too big to fit on 8 HPUs as you said earlier

**Comment by regisss** [comment]
Yes, you can try with `bigscience/bloomz-7b1`

**Comment by regisss** [comment]
@Abhaycnvrg Let me know if your issue is solved so that we close this.

**Comment by Abhaycnvrg** [comment]
yup! thanks a ton!
