### ISSUE TITLE
Will Hugging Face support GLM series models (ChatGLM-6B, ChatGLM2-6B ...) in Transformers?

### ISSUE THREAD

**Issue by jychen-habana** [huggingface/optimum-habana#299]
### Feature request

We plan to enable ChatGLM-6B, ChatGLM2-6B series models on HPU but found that the models are not in Transformers. 

Model definitions and weights are all on Hugging Face model card:
ChatGLM-6B: https://huggingface.co/THUDM/chatglm-6b
ChatGLM2-6B:  https://huggingface.co/THUDM/chatglm2-6b

Is that possible to support these models in Transformers so that optimum-habana could do some hijacking and then enable them on HPU? 

### Motivation

enable ChatGLM-6B, ChatGLM2-6B on HPU

### Your contribution

enable ChatGLM-6B, ChatGLM2-6B on HPU

**Comment by regisss** [comment]
@jychen-habana At the moment it is not planned to integrate it directly into Transformers, see here: https://github.com/huggingface/transformers/issues/22290

So, if you really want to add support for it on HPU, one solution is to adapt and optimize the modeling code of the hub repos and we could store it in Optimum Habana. But that leads to potential issues:

- Is the modeling code the same in all ChatGLM hub repos?
- There will be extra work if it is integrated into Transformers some day, even though it doesn't seem likely at this point.

Happy to review a PR if you want to add modeling code in Optimum Habana :slightly_smiling_face:

**Comment by jychen-habana** [comment]
Thanks! @regisss 
If that case, we will make a fork version of the original ChatGLM series models with HPU modifications first. And then migrate them to optimum-habana after Transformers integrate the models.

**Comment by jychen-habana** [comment]
Hi @regisss We plan to put the two models to optimum-habana and also Habana model card:

For modified 'modified cli_demo.py, web_demo.py, also README and requirements.txt, … ' of this [THUDM Github]( https://github.com/THUDM/ChatGLM2-6B/tree/main), we plan to put them to a to folder (like 'chat-glm') under optimum-habana/examples

For modified 'modeling_chatglm.py' and model weights of this HF model card [THUDM/chatglm2-6b](https://huggingface.co/THUDM/chatglm2-6b/tree/main), currently we are thinking of just putting modified modeling script to [Habana Model Card](https://huggingface.co/Habana), like 'Habana/chatglm2-6b', but I have a concern is that when we call:
```python
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).cuda()
````
1. Will optimum-habana automatically download both “THUDM/chatglm2-6b” and “Habana/chatglm2-6b”? 
2. Where would the original modeling_chatglm.py in the local cached hub be replaced with the modified version of “Habana/chatglm2-6b”?

Or can we just fork the whole [THUDM/chatglm2-6b](https://huggingface.co/THUDM/chatglm2-6b/tree/main) including model weights, then push to [Habana Model Card](https://huggingface.co/Habana) with modified modeling scripts.
