### ISSUE TITLE
ImportError: No module named optimum.habana.distributed

### ISSUE THREAD

**Issue by Abhaycnvrg** [huggingface/optimum-habana#300]
### System Info

```shell
Optimum Habana : 1.6.0
SynapseAI : 1.10.0
Docker Image : vault.habana.ai/gaudi-docker/1.10.0/amzn2/habanalabs/pytorch-installer-2.0.1:latest
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Pull this image **vault.habana.ai/gaudi-docker/1.10.0/amzn2/habanalabs/pytorch-installer-2.0.1:latest** into the cnvrg repository
2. Run the following commands
3. pip install optimum[habana]
4. cd optimum-habana/examples/text-generation
5. pip install -r requirements.txt
6. pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.10.0
7. python ../gaudi_spawn.py --use_deepspeed --world_size 2 run_generation.py \
--model_name_or_path bigscience\bloom-560m \
--use_hpu_graphs \
--use_kv_cache \
--max_new_tokens 100 \
--do_sample \
--prompt "Tell me a poem about stone and water"

### Expected behavior

it should either generate text or give permission issue error

**Comment by regisss** [comment]
I cannot reproduce it. Could you print the whole error message here please @Abhaycnvrg ?
