### ISSUE TITLE
dock build fail in https://github.com/huggingface/optimum-habana/tree/main/text-generation-inference

### ISSUE THREAD

**Issue by sywangyi** [huggingface/optimum-habana#337]
shall we need to upgrade text-generation-inference code to main?
see https://github.com/huggingface/text-generation-inference/issues/840

I meet the same issue when build the docker image for TGI of habana

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

 https://github.com/huggingface/optimum-habana/tree/main/text-generation-inference

docker build -t tgi_gaudi .

### Expected behavior

build success

**Comment by sywangyi** [comment]
@regisss

**Comment by regisss** [comment]
Could you try pining `tokenizers` to `v0.13.4` [here](https://github.com/huggingface/optimum-habana/blob/bb715f6dbf17cd42e19866eac2afc23bb8cb8a97/text-generation-inference/server/requirements.txt#L66) and [there](https://github.com/huggingface/optimum-habana/blob/bb715f6dbf17cd42e19866eac2afc23bb8cb8a97/text-generation-inference/server/pyproject.toml#L25) and let me know if that works?

I'll upgrade to TGI v1.0 a bit later.

**Comment by sywangyi** [comment]
@regisss  does not work by pining tokenizers to v0.13.4

error log is
![image](https://github.com/huggingface/optimum-habana/assets/36058628/57b8a472-e61b-4d51-b384-4435743f0ff6)

**Comment by regisss** [comment]
Okay, I'll try to cherry-pick https://github.com/huggingface/text-generation-inference/pull/838

**Comment by Narsil** [comment]
Thanks !  Sorry about the BC

**Comment by htang2012** [comment]
got the same issue, glad to see a quick fix.

**Comment by skaulintel** [comment]
@regisss also seeing the same issue. Is there a PR for this yet? Let me know if I can help.

**Comment by regisss** [comment]
@skaulintel  It should come on Monday or Tuesday

**Comment by regisss** [comment]
@sywangyi @htang2012 @skaulintel I opened #373, could you try it to see if you can successfully build a Docker image, send request and get plausible results please? I jut tried BLOOM but we can add support for other models pretty easily.

**Comment by sywangyi** [comment]
Hi, @regisss , I tried 373, and it works for docker image build and bloom case in the README. I think you could merge the PR/

**Comment by regisss** [comment]
Sounds good, and we'll open new PRs to add models and if we find bugs
