### ISSUE TITLE
setup.py need to be updated to 0.22.0 for accelerate

### ISSUE THREAD

**Issue by LeoZhao-Habana** [huggingface/optimum-habana#371]
### System Info

```shell
optimum habana: 1.8.0-dev0
transformers： 4.32.1
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. pip install .
2. cd examples/text-generation
3. pip install -r requirements.txt
4. python run_generation.py \
--model_name_or_path gpt2 \
--use_hpu_graphs \
--use_kv_cache \
--max_new_tokens 100 \
--do_sample \
--prompt "Here is my prompt"

### Expected behavior

run sucessfully, but current result is reporting "cannot import name 'AutocastKwargs' from ...
![Weixin Image_20230829110035](https://github.com/huggingface/optimum-habana/assets/48052473/41001185-5aeb-4398-b5e6-9864ba19aed2)

**Comment by regisss** [comment]
Good catch @LeoZhao-Habana! Will do it
