### ISSUE TITLE
tgi server keeps repeating short words in the output.

### ISSUE THREAD

**Issue by htang2012** [huggingface/optimum-habana#383]
### System Info

```shell
optimum-habana                         1.7.2
text-generation                        0.6.0
text-generation-server                 1.0.3
langchain                              0.0.279
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Step to reproduce:
1. start text-generation-server following the instruction:
https://github.com/huggingface/optimum-habana/tree/main/text-generation-inference
2. launch bash in the docker,
3. inside the docker:
     pip install langchain text-generation
4. python run the following script-- lclient.py

from langchain import  HuggingFaceTextGenInference
llm = HuggingFaceTextGenInference(
    inference_server_url="http://127.0.0.1:80",
    max_new_tokens=64,
    top_k=10,
    top_p=0.95,
    typical_p=0.95,
    temperature=0.01,
    repetition_penalty=1.03,
)
output = llm("What is Machine Learning?")

print(output)

5. noticed: 
on the client side, for the first launch, the output is as follows which is ok.

root@653f39f1fd71:/text-gen/client# python lclient.py

 Learn More
The purpose of this article is to show you how to use the machine learning algorithm to solve a problem. The goal of this article is to demonstrate that the machine learning algorithm can solve many problems. Learn More
The first section of our book is about general computer programs and their usage. We will cover

then after the first launch, the output is as follows.

root@653f39f1fd71:/text-gen/client# python lclient.py
 explain give cover give then then give then give then cover cover give explain discuss explain discuss cover then give discuss give cover then give then explain give then explain explain discuss explain cover give give discuss cover explain then discuss cover discuss then cover explain discuss then explain explain then cover give cover explain discuss cover give explain explain give cover cover discuss

root@653f39f1fd71:/text-gen/client# python lc.py
 give give explain explain explain then cover then cover explain give then give then discuss explain cover give give give give then then explain then cover explain cover then discuss cover cover explain then give cover then cover then discuss then cover cover give explain discuss then discuss cover cover cover explain explain explain then then explain give give cover discuss give give then

root@653f39f1fd71:/text-gen/client# python lc.py
 cover give discuss explain explain cover then explain then explain give discuss explain discuss discuss discuss give give then then give cover cover explain cover then give then then give then discuss discuss then discuss explain then explain then give give then explain explain cover discuss discuss cover discuss discuss discuss discuss then discuss cover discuss then explain discuss give then cover give discuss
 

### Expected behavior

The second client request should yield samiliar expected output as the first.

**Comment by avinashkarani** [comment]
I am also facing similar issue when running with Lang chain (played around with temperature settings to improve response quality). First response is good but subsequent query response is gibberish. Same behavior observed irrespective of model (tried Bloomz,Llama 2).

**Comment by avinashkarani** [comment]
By cache=False in the Lang chain call along with higher max token value, we are able to avoid this issue. 

llm_local = HuggingFaceTextGenInference(
    inference_server_url=inference_server_url_local,
    max_new_tokens=1024,
    top_k=10,
    top_p=0.95,
    typical_p=0.95,
    temperature=1,
    repetition_penalty=1.03,
    cache= False,
)

Another observation, whenever response gets truncated due to max_new_tokens subsequent responses are repeating the last word in the truncated response. Increasing max tokens helped here.

**Comment by htang2012** [comment]
> By adding cache=False in the Lang chain call along with higher max token value, we are able to avoid this issue.
> 
> llm_local = HuggingFaceTextGenInference( inference_server_url=inference_server_url_local, max_new_tokens=1024, top_k=10, top_p=0.95, typical_p=0.95, temperature=1, repetition_penalty=1.03, cache= False, )
> 
> Another observation, whenever response gets truncated due to max_new_tokens subsequent responses are repeating the last word in the truncated response. Increasing max tokens helped here.

Sorry, in my case,  bigscience/bloom-560m. I still got gibberish words after cache=False is set

**Comment by regisss** [comment]
@htang2012 @avinashkarani Could you try now? #404 should have solved this issue

**Comment by regisss** [comment]
Has this issue been solved?

**Comment by avinashkarani** [comment]
@regisss I got a chance to test this, and issue seems to be resolved now. Thanks for the update
