### ISSUE TITLE
Does it make sense to also provide an option of max input tokens for text generation ?

### ISSUE THREAD

**Issue by puneeshkhanna** [huggingface/optimum-habana#423]
### Feature request

Right now we tokenize as below and based upon input sentences in the batch, the input ids are padded.
input_tokens = tokenizer.batch_encode_plus(input_sentences, return_tensors="pt", padding=True)

What if the next batch of data exceeds the above input tokens length which will trigger recompilations.

Would it not be better if we also introduce an argument of max input length and tokenize as below using padding to max length and truncation to True:

input_tokens = tokenizer.batch_encode_plus(batch_sentences, padding='max_length', truncation=True, max_length=args.max_input_length)

### Motivation

Avoid graph recompilations.

### Your contribution

Yes if we agree.

**Comment by regisss** [comment]
Yes sure, that would definitely make sense. Are you specifically talking about the text-generation example or TGI?

**Comment by puneeshkhanna** [comment]
Text generation example script (run_generation.py) for now. There might be other places too where we may want such a logic but I haven't checked yet.

**Comment by regisss** [comment]
Sounds good :+1: 
That's actually what I did here for the case where a dataset is provided: https://github.com/huggingface/optimum-habana/blob/e351f7c0968cf5abeb21db0c58611578e764c7bc/examples/text-generation/run_generation.py#L522C38-L527
But it's quite dirty and your solution is more generic :slightly_smiling_face:

**Comment by puneeshkhanna** [comment]
Ok I will push for text generation script first. I guess it will also help anyone to experiment with any input seq len to verify performance.
