### ISSUE TITLE
FileNotFoundError: Couldn't find a dataset script

### ISSUE THREAD

**Issue by OmerBoucris** [huggingface/optimum-habana#432]
### System Info

```shell
GPT-NeoX Text-generation Training on HLS2 

--branch v1.7.3(Fail)

--branch v1.7.4(Fail)

 --branch v1.7.5(Fail)

 
`FileNotFoundError: Couldn't find a dataset script at /root/optimum-habana/examples/text-generation/wikitext-2-raw-v1/wikitext-2-raw-v1.py or any data file in the same directory. Couldn't find 'wikitext-2-raw-v1' on the Hugging Face Hub either: FileNotFoundError: Dataset 'wikitext-2-raw-v1' doesn't exist on the Hub. If the repo is private or gated, make sure to log in with `huggingface-cli login`. 
I encountered this following error:


Full log:

https://logs-browser.k8s-infra.habana-labs.com/files/qa-tester-9-004527355-2642-tfjob/log.txt
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

pip install --upgrade-strategy eager optimum[habana]
git clone https://github.com/huggingface/optimum-habana --branch v1.7.4
pip install -r requirements.txt
pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.11.0
python ../gaudi_spawn.py --use_deepspeed --world_size number_of_devices run_generation.py ARGS

python run_generation.py \
--model_name_or_path gpt2 \
--use_hpu_graphs \
--use_kv_cache \
--max_new_tokens 100 \
--do_sample \
--prompt "Here is my prompt"

### Expected behavior

Pass

**Comment by regisss** [comment]
Hi @OmerBoucris, not sure how to reproduce this error as the command you gave doesn't contain any argument linked to `wikitext-2-raw-v1`.
My best guess is that you tried to load a dataset named `wikitext-2-raw-v1`, while the dataset you are looking for is [wikitext](https://huggingface.co/datasets/wikitext) with the config `wikitext-2-raw-v1`.

Besides, the text-generation exampel does do any training. I think what you want to do is to run the language modeling example here: https://github.com/huggingface/optimum-habana/tree/main/examples/language-modeling#multi-node-training-with-deepspeed-gpt-neox

**Comment by OmerBoucris** [comment]
@regisss Hey, I run this cmd:

`python ../gaudi_spawn.py \
    --hostfile path_to_my_hostfile --world_size 16 --use_deepspeed run_clm.py \
    --model_name_or_path EleutherAI/gpt-neox-20b \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 2\
    --per_device_eval_batch_size 2 \
    --do_train \
    --do_eval \
    --output_dir /tmp/test-clm-xl-bs2 \
    --gaudi_config_name Habana/gpt2 \
    --use_habana \
    --use_lazy_mode \
    --gradient_checkpointing \
    --use_hpu_graphs_for_inference \
    --throughput_warmup_steps 3 \
    --deepspeed path_for_deepspeed_config`

and faced with this following error:
`  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/distributed/distributed_runner.py", line 235, in process_hostfile
    raise ValueError(f"Unable to find hostfile at {self._hostfile}.")
ValueError: Unable to find hostfile at path_to_my_hostfile.
. Output: [2023-10-02 12:18:16,276] [INFO] [real_accelerator.py:123:get_accelerator] Setting ds_accelerator to hpu (auto detect)
. Return status: 1`

Am I run that cmd as you mentioned ? if no please let me know and gimme please the full cmd

**Comment by regisss** [comment]
Yes, that's the right command but `path_to_my_hostfile` and `path_for_deepspeed_config` needs to be valid paths:
- `path_to_my_hostfile` must be a valid path to an existing file listing the hosts, have you written one? If not, take a look at the doc here: https://github.com/huggingface/optimum-habana/tree/main/examples/multi-node-training#hostfile
- `path_for_deepspeed_config` must be a valid path to an existing JSON file that specifies the DeepSpeed configuration to use, have you got one? If not, here is one that should work with GPT-NeoX: https://github.com/huggingface/optimum-habana/blob/main/tests/configs/deepspeed_zero_2.json

**Comment by regisss** [comment]
@OmerBoucris Have you managed to solve your problem?
