### ISSUE TITLE
Latest version of optimum-habana does not work with transformers==4.32.1

### ISSUE THREAD

**Issue by amukho** [huggingface/optimum-habana#460]
### System Info

```shell
optimum-habana: 1.8.0.dev0
transformers: 4.32.1 (preinstalled)

Following message seen when installing optimum-habana:
Requirement already satisfied: transformers>=4.32.0
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python run_qa.py \
  --model_name_or_path bert-large-uncased-whole-word-masking \
  --gaudi_config_name Habana/bert-large-uncased-whole-word-masking \
  --dataset_name squad \
  --do_train \
  --do_eval \
  --per_device_train_batch_size 24 \
  --per_device_eval_batch_size 8 \
  --learning_rate 3e-5 \
  --num_train_epochs 1 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /tmp/squad/ \
  --use_habana \
  --use_lazy_mode \
  --use_hpu_graphs_for_inference \
  --bf16 \
  --throughput_warmup_steps 3

Fails with the following error:
ModuleNotFoundError: No module named 'transformers.integrations.deepspeed'; 'transformers.integrations' is not a package

### Expected behavior

Since transformers 4.32.0 is no longer supported with latest optimum-habana it should install the minimum version that is supported

**Comment by regisss** [comment]
Good catch! #462 will fix this.
