### ISSUE TITLE
Repo card metadata block was not found. Setting CardData to empty

### ISSUE THREAD

**Issue by sureshnam** [huggingface/optimum-habana#491]
### System Info

```shell
optimum-habana          1.8.0
docker vault.habana.ai/gaudi-docker/1.12.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:latest
Synapse Version 1.12.0-480 

https://github.com/huggingface/optimum-habana/tree/ee5e8fc39e78800eb3763d048192bef036fadc4c/examples/contrastive-image-text

The step in Readme fails with "Repo card metadata block was not found. Setting CardData to empty"
The dataset validation step, pasted below. 

import os
import datasets

COCO_DIR = os.path.join(os.getcwd(), "data")
ds = datasets.load_dataset("ydshieh/coco_dataset_script", "2017", data_dir=COCO_DIR)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just launch the docker and follow the Readme steps, you see this issue.

### Expected behavior

I assume dataset get loaded , Just see no response

**Comment by regisss** [comment]
Where have you downloaded the zip files? It's likely that they are not in a folder called `data` in the current directory.
