### ISSUE TITLE
StableDiffusion v2.1 produces incorrect images

### ISSUE THREAD

**Issue by mgawarkiewicz** [huggingface/optimum-habana#547]
### System Info

```shell
diffusers==0.23.1
habana-torch-plugin==1.13.0.463
optimum==1.14.1
optimum-habana==1.8.1
transformers==4.34.1
optimum-habana repo (examples) on main (which is c7eb594aa9eaf45ef8e4ac8f4a20d0038be50aa6)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. git clone https://github.com/huggingface/optimum-habana.git /root/optimum-habana
2. pip install optimum[habana]
3. cd /root/optimum-habana/examples/stable-diffusion/ 
4. python text_to_image_generation.py   --model_name_or_path stabilityai/stable-diffusion-2-1   --prompts "a professional photograph of an astronaut riding a horse"   --num_images_per_prompt 4   --batch_size 1   --height 768   --width 768   --image_save_dir stable_diffusion_images   --use_habana   --use_hpu_graphs   --gaudi_config Habana/stable-diffusion-2

### Expected behavior

Generated images are incorrect. An astronaut on a horse is expected, but a construction site (?) is produced as a first output image: ![image_1](https://github.com/huggingface/optimum-habana/assets/72728821/cc56d09c-45ed-4bdc-9e63-bfb7518cf28e)

**Comment by mgawarkiewicz** [comment]
When I switch back to optimum-habana v1.7.5 (with pip install optimum-habana==1.7.5 on top of the setup described in the ticket, meaning all other packages remain in the unchanged versions) then the issue is gone, generated images are correct:
![image_1_1 7 5](https://github.com/huggingface/optimum-habana/assets/72728821/64514dab-b377-4fce-ad42-5729fe2440f3)

**Comment by regisss** [comment]
I ca

**Comment by regisss** [comment]
@mgawarkiewicz https://github.com/huggingface/optimum-habana/pull/548 will fix that
