### ISSUE TITLE
Increase in device memory usage with peft version 0.7.0

### ISSUE THREAD

**Issue by vivekgoe** [huggingface/optimum-habana#590]
### System Info

```shell
Optimum Habana - 1.9.0
Synapse - 1.13.0

Execution of Falcon-180B fine-tuning with LoRA on 8xGaudi2 (using command shared in examples/language-modeling) fails with device OOM error when latest version of peft (==0.7.0) is installed, same works fine if peft is downgraded to 0.6.2.
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to reproduce the behavior,
1.  Use command shared for Falcon-180B fine-tuning under examples/language-modeling/README.md on 8xGaudi2 with above provided configuration or latest Optimum Habana. Following error shall be seen

FATAL ERROR :: MODULE:PT_DEVMEM Allocation failed

### Expected behavior

Falcon-180B fine-tuning (full 3 epochs) should complete.

**Comment by vivekgoe** [comment]
@regisss shall I go ahead and close this issue? or do we want to investigate further on why "peft == 0.7.0" is causing increase in device memory consumption.

**Comment by regisss** [comment]
Let's keep it open for now. I'll try to investigate this and pass it to the PEFT team if I find anything.

**Comment by vivekgoe** [comment]
@regisss I bisected PEFT commits between 0.6.2 and 0.7.0. Device memory increase started from this commit https://github.com/huggingface/peft/commit/5a3a5acff2d679358251742564f7b12efbee3a41 
Perhaps this information can help in your investigation and discussions with PEFT team.

**Comment by vivekgoe** [comment]
@regisss I bisected PEFT commits between 0.6.2 and 0.7.0. Increase in device memory is coming from this commit https://github.com/huggingface/peft/commit/5a3a5acff2d679358251742564f7b12efbee3a41

**Comment by regisss** [comment]
Thanks @vivekgoe!
@younesbelkada Any idea regarding what could lead to a higher memory usage in this commit?

**Comment by vivekgoe** [comment]
@regisss  @younesbelkada issue seems to be coming from FalconLinear layer here
https://github.com/huggingface/transformers/blob/09eb11a1bd6e77833fde7020efc57e6a804e4e8a/src/transformers/models/falcon/modeling_falcon.py#L75  
If I replace all instances of FalconLinear in the model with nn.Linear then memory footprint goes back to numbers before https://github.com/huggingface/peft/commit/5a3a5acff2d679358251742564f7b12efbee3a41

**Comment by sywangyi** [comment]
https://github.com/huggingface/optimum-habana/pull/895

**Comment by regisss** [comment]
To give more details, sharing here what I wrote on Slack (internal to HF):

> Coming back to this, it's actually not an issue on PEFT side. Before the commit linked above, linear layers were replaced by [Linear](https://github.com/huggingface/peft/blob/70302d7b4fc667f6b2e80ac1b8cccde081270d1e/src/peft/tuners/lora/layer.py#L191) , where the forward calls `F.linear`. After this commit, the forward will call the base layer, which makes sense.
Since Falcon's linear layer implementation is a bit different (see [here](https://github.com/huggingface/transformers/blob/ec92f983af5295fc92414a37b988d8384785988a/src/transformers/models/falcon/modeling_falcon.py#L71)), this means that:
> - before this commit, the forward was `F.linear`
> - after, it is `FalconLinear.forward`
>
> So here is the difference that triggered the OOM error on Gaudi.
