### ISSUE TITLE
Facing issue while running the git repository for text generation

### ISSUE THREAD

**Issue by VenkateshPasumarti** [huggingface/optimum-habana#599]
### System Info

```shell
Unable to download dataloader is the error being displayed while running it on AWS DL1 instance 
Ubuntu Version 20.04
Python PyTorch: 3.8

can you please give the installations and updated versions list
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

no idea why i am getting that error

### Expected behavior

can you please give the installations and updated versions list

**Comment by regisss** [comment]
@VenkateshPasumarti Can you share the command you executed and the whole error message you got please?
