### ISSUE TITLE
run_lora_clm.py support for other datasets

### ISSUE THREAD

**Issue by tmabraham** [huggingface/optimum-habana#629]
### Feature request

right now [the script](https://github.com/huggingface/optimum-habana/blob/main/examples/language-modeling/run_lora_clm.py) is hardcoded for either `"tatsu-lab/alpaca"` or `"timdettmers/openassistant-guanaco"` and using any other dataset throws an error.

### Motivation

It would be nice to be able to finetune on our own datasets.

### Your contribution

Happy to test any code out for this...

**Comment by regisss** [comment]
Yes, I agree that would be much better.
Can you share a command line that fails? And the error message you get please?

**Comment by dmsuehir** [comment]
I posted PR #955 that fixes this issue and will allow other datasets to be used with `run_lora_clm.py`. I tried it with several different datasets to check the functionality, but please let me know if there's a specific one that you'd like me to try.
