### ISSUE TITLE
ENABLE_CONSOLE disrupts version checks in examples

### ISSUE THREAD

**Issue by vidyasiv** [huggingface/optimum-habana#684]
### System Info

```shell
optimum-habana: 1.10.0.dev0
SynapseAI: 1.13.0
Docker Image: vault.habana.ai/gaudi-docker/1.13.0/ubuntu20.04/habanalabs/pytorch-installer-2.1.0:1.13.0-463
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

1. export ENABLE_CONSOLE=True or ENABLE_CONSOLE=false
2. Run any example in optimum-habana that has a version check or run the following snippet
```
try:
    from optimum.habana.utils import check_optimum_habana_min_version
except ImportError:

    def check_optimum_habana_min_version(*a, **b):
        return ()
# Will error if the minimal version of Optimum Habana is not installed. Remove at your own risks.
check_optimum_habana_min_version("1.8.1")

```
And you see output
```
Traceback (most recent call last):
  File "version.py", line 3, in <module>
    from optimum.habana.utils import check_optimum_habana_min_version
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/__init__.py", line 29, in <module>
    check_synapse_version()
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/utils.py", line 190, in check_synapse_version
    driver_version = get_driver_version()
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/utils.py", line 234, in get_driver_version
    return version.parse(output.stdout.split("\n")[2].replace(" ", "").split(":")[1][:-1].split("-")[0])
IndexError: list index out of range
```

### Expected behavior

- ENABLE_CONSOLE could pick up "True" or "true" (optional)
- optimum-habana should handle the case when ENABLE_CONSOLE is false gracefully - one option is to not check version if ENABLE_CONSOLE is disabled and print a warning about the same

**Comment by vidyasiv** [comment]
I'd be happy to help fix this if needed, let me know what the recommendation is for handling this case.

**Comment by regisss** [comment]
Good catch @vidyasiv!
So `hl-smi` doesn't return anything to the console if `ENABLE_CONSOLE` is set to `True` or `false`.
As per your suggestion, let's add a check here: https://github.com/huggingface/optimum-habana/blob/f096980bf0d192cc3d23d22a32f2479aa0617571/optimum/habana/utils.py#L232-L234
Something like:
```py
if output.returncode == 0 and output.stdout:
    return version.parse(...)
else:
    logger.warning("Couldn't get the output of `hl-smi` so the version check is skipped")
```

WDYT? This is just a proposition, feel free to open a PR to fix this :slightly_smiling_face:
