### ISSUE TITLE
[Feature request] Mistral implementation for language modeling?

### ISSUE THREAD

**Issue by timpal0l** [huggingface/optimum-habana#696]
### Feature request

It looks like currently there is no support for training using the mistral7b architecture, only inference for 1 card.

### Motivation

Missing the currently most popular open source model.

### Your contribution

Can help if guided where the implementation needs to happen.

**Comment by regisss** [comment]
Hi @timpal0l, the table in the README only accounts for the cases that have been heavily tested and are part of our nightly CI. However, there are still many other cases that could work.

In the case of Mistral, [this LoRA example](https://github.com/huggingface/optimum-habana/tree/main/examples/language-modeling#peft) (single-card finetuning of Llama1-7B) runs fine with [mistralai/Mistral-7B-v0.1](https://huggingface.co/mistralai/Mistral-7B-v0.1) and a batch size of 8 for instance. How would you like to train it? LoRA? DeepSpeed?

**Comment by timpal0l** [comment]
@regisss Thanks for your fast answer, I would like to do a full finetune, so not LoRA or QLoRA, ideally DeepSpeed if possible. Thanks!

**Comment by regisss** [comment]
The [language modeling example](https://github.com/huggingface/optimum-habana/tree/main/examples/language-modeling#using-deepspeed) runs without issues on Gaudi2 with DeepSpeed ZeRO-2:
```
python ../gaudi_spawn.py \
    --world_size 8 --use_deepspeed run_clm.py \
    --model_name_or_path mistralai/Mistral-7B-v0.1 \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --learning_rate 4e-4 \
    --output_dir /tmp/test-clm \
    --gaudi_config_name Habana/gpt2 \
    --use_habana \
    --use_lazy_mode \
    --use_hpu_graphs_for_inference \
    --gradient_checkpointing \
    --use_cache False \
    --throughput_warmup_steps 3 \
    --deepspeed path_to_my_deepspeed_config
```
You can use this DeepSpeed configuration for example: https://github.com/huggingface/optimum-habana/blob/main/tests/configs/deepspeed_zero_2.json

I've not tried ZeRO-3 but I think it should work too :slightly_smiling_face:
