### ISSUE TITLE
eager optimum[habana] pointing to optimum-habana 1.10.4

### ISSUE THREAD

**Issue by 12010486** [huggingface/optimum-habana#969]
### System Info

```shell
Following instructions in https://github.com/huggingface/optimum-habana/tree/main
there is an error in **Option 1: Use the latest stable release** as with
`pip install --upgrade-strategy eager optimum[habana]` 
the optimum-habana version is the 1.10.4, not the latest stable (v1.11.1)
Latest commit on the main branch is e2d028e626e6c26e269302e8c042852d9b41c1a4
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`pip install --upgrade-strategy eager optimum[habana]`
`pip list | grep optimum-habana`

### Expected behavior

Latest stable version in documentation is intended to be 1.11.1, at least looking at:
`cd optimum-habana && git checkout v1.11.1`

**Comment by regisss** [comment]
I can reproduce, I'm going to fix it

**Comment by regisss** [comment]
@12010486 Can you try
```
pip install --upgrade-strategy eager optimum[habana]
```
again and let me know if that works now?

**Comment by 12010486** [comment]
Works again, thanks!
I'm closing it
